List, Numpy Array, Numpy Matrix, Dictionary

In [5]:
nm = [1,2,3,4,5]
print(nm)

[1, 2, 3, 4, 5]


In [18]:
bd = list(range(10))
type(bd)
dir(bd)
import random
x = 0
list_1 = []
while x <= 100: 
    list_1.append(random.randrange(-1, 2))
    x += 1
    
print(list_1)  
print()

print(list_1.count(-1), list_1.count(0), list_1.count(1))





[-1, -1, 1, -1, 1, 1, -1, 1, 0, 0, -1, 0, 1, 1, -1, -1, -1, 1, 0, 0, -1, 0, 1, 0, 0, 0, 0, 0, 1, -1, 1, -1, -1, -1, 0, -1, -1, -1, 1, 0, 1, -1, 0, -1, 0, 1, 0, 1, 0, 1, -1, 0, -1, 0, 0, 1, 1, 1, 0, -1, 1, -1, -1, -1, 0, -1, -1, -1, 0, -1, 1, -1, 1, 1, -1, 1, 1, -1, 1, 1, 1, 0, 1, 0, 0, 1, -1, 0, 1, 1, -1, 1, 0, 1, 1, -1, -1, -1, 0, 0, 1]

36 30 35


In [20]:
st = 'abcdef'
slt  = list(st)
print(st)
slt

abcdef


['a', 'b', 'c', 'd', 'e', 'f']

In [5]:
num1 = [1,2,3,4,5]
num0 = [10,20,30,40,50]
num2 = [ x*y for x in num1 for y in num0 ]
num_pair = [(x* y) for x, y in zip(num1, num0)]
print(num_pair)
print()
print(num2)

[10, 40, 90, 160, 250]

[10, 20, 30, 40, 50, 20, 40, 60, 80, 100, 30, 60, 90, 120, 150, 40, 80, 120, 160, 200, 50, 100, 150, 200, 250]


In [24]:
# num1 = [1,2,3,4,5]
# num0 = [10,20,30,40,50]
# sz = len(num1)
# num2 = [ num1[i]*num0[i] for i in range(sz)]
# print(num2)

def multiply_list(lst_1, lst_2):
    if len(lst_1) != len(lst_2):
        return """
        Error
        List Dimension is unequal
        """.strip()
    else:
        mult = [ lst_1[i]*lst_2[i] for i in range(len(lst_1))]
        return mult
    
multiply_list([1,3,4,5], [2,3,4,8])

[2, 9, 16, 40]

### List Indexing

In [30]:
num = list(range(2,102,2))
a = num[20]
b = num[-13]
print(a)
print(b)

42
76


### List Slicing

In [41]:
num = list(range(100))
part = num[0:9]
part2 = num[:9]
part3 = num[80:]
part4 = num[0::2]
pos = [12, 14, 17, 29]
part5 = [num[i] for i in pos]
print(part5)

[12, 14, 17, 29]


### Updating List
Note that a list is a mutable object

In [7]:
num = [3, 5, 7, 9, 13]
num2 = [3, 5, 7, 9, 13]

print(id(num))
num[0] = 20
print(num)
print(id(num))

num[0:3] = [30,40,50]
print(num)

92555208
[20, 5, 7, 9, 13]
92555208
[30, 40, 50, 9, 13]


In [54]:
s1 = 'abc'
print(id(s1))
s1 += "def"
print(id(s1))
print(s1)

2312928574576
2313027683584
abcdef


### Properties of List

In [56]:
num = []
num.append(2)
num.append("abc")
num.append([4,5,6])
print(num)

[2, 'abc', [4, 5, 6]]


In [60]:
num = []
num.append(2)
num.append("abc")
num.append([4,5,6])
f = num.pop()
print(f)
print(num)

[4, 5, 6]
[2, 'abc']


### Tuple
Tuple is like list but it is immutable 

In [69]:
tup = (1,2,3,4)
tup2 = (11,) + tup[1:]
print(tup2)

(11, 2, 3, 4)


In [8]:

vals = range(100)
x,y = [2*v for v in vals], [v/3 for v in vals]
print(x)
print()
print(y)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198]

[0.0, 0.3333333333333333, 0.6666666666666666, 1.0, 1.3333333333333333, 1.6666666666666667, 2.0, 2.3333333333333335, 2.6666666666666665, 3.0, 3.3333333333333335, 3.6666666666666665, 4.0, 4.333333333333333, 4.666666666666667, 5.0, 5.333333333333333, 5.666666666666667, 6.0, 6.333333333333333, 6.666666666666667, 7.0, 7.333333333333333, 7.666666666666667, 8.0, 8.333333333333334, 8.666666666666666, 9.0, 9.333333333333334, 9.666666666666666, 10.0, 10.333333333333334, 10.666666666666666, 11.0, 11.333333333333334, 11.666666666666666, 12.0, 12.3333333333333

### Set
A collection of unique elements

In [78]:
lt = [1,2,3,4,4,4,5,5,5,6,7]
se = set(lt)
print(se)
se2 = { 2,3,4,5,6 , 6,7}
print(se2)


{1, 2, 3, 4, 5, 6, 7}
{2, 3, 4, 5, 6, 7}


In [10]:
import numpy as np
ar = np.array([1,2,3,4])
ar2 = ar*ar
print(ar2)

[ 1  4  9 16]


In [91]:
ar3 = np.array([1,2,3, "abc"])
print(ar3)

['1' '2' '3' 'abc']


In [11]:
ar3 = np.array([1,2,3, 9])
print(ar3)
ar4 = np.ones([3,2])
lt = [ [1,1], [1,1], [1,1] ]
ar5 = np.array(lt)
ar6 = np.zeros([10,4]) + 5
print(ar6)

[1 2 3 9]
[[ 5.  5.  5.  5.]
 [ 5.  5.  5.  5.]
 [ 5.  5.  5.  5.]
 [ 5.  5.  5.  5.]
 [ 5.  5.  5.  5.]
 [ 5.  5.  5.  5.]
 [ 5.  5.  5.  5.]
 [ 5.  5.  5.  5.]
 [ 5.  5.  5.  5.]
 [ 5.  5.  5.  5.]]


In [1]:
import numpy as np
C = np.array([ [2,1,-1], [1,-3,2], [3,2,-3] ])

D = np.array([ [2], [3], [-3] ])
Cm = np.matrix(C)
Dm = np.matrix(D)
X1 = np.multiply(Cm, Cm)
X = Cm.I * Dm
print(X1)
print()
print(X)
print()

E = C * D
print(E)


[[4 1 1]
 [1 9 4]
 [9 4 9]]

[[ 2.]
 [ 3.]
 [ 5.]]

[[ 4  2 -2]
 [ 3 -9  6]
 [-9 -6  9]]


In [138]:
sm = np.sum(C)
print(sm)

4


In [20]:
Dist = [[1,2],[1,1],[1.5,1.5],[3,4],[3.5,3.5], [4,4]]

Dist = np.array(Dist)
print(Dist)
Center = np.array([2, 3])
r,c = Dist.shape
# print(r, c)
print(np.sum((Dist[5,:] - Center)**2))

np.tile(Center, [6,1])
print("row: " + str(r) , "column: " + str(c))
result = [np.sqrt( np.sum( (Dist[i,:] - Center)**2) )  for i in range(r)]
result2 = np.sqrt(np.sum((np.tile(Center, [6,1]) - Dist)**2, 1))
(np.array(result).T)
# print(result2)

[[ 1.   2. ]
 [ 1.   1. ]
 [ 1.5  1.5]
 [ 3.   4. ]
 [ 3.5  3.5]
 [ 4.   4. ]]
5.0
row: 6 column: 2
[ 1.41421356  2.23606798  1.58113883  1.41421356  1.58113883  2.23606798]
