### Dictionary

In [1]:
dict_1 = { "john":20,"james":50,"femi":35,"mike":43 }

print(dict_1)

{'john': 20, 'james': 50, 'femi': 35, 'mike': 43}


### Using Keys To Get Values In Dictionary

In [2]:
sc = dict_1['john']

print(sc)

20


### Checking If A Key Exists

In [3]:
ky = 'john'
if ky in dict_1:
    print('Yes')
else:
    print('No')

Yes


In [6]:
allKeys = list(dict_1.keys())
for kt in allKeys:
    print(kt)
print(allKeys)

john
james
femi
mike
['john', 'james', 'femi', 'mike']


In [7]:
dir(dict_1)

['__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

In [14]:
v = dict_1.get('johnny', None)
print(v)


False


In [30]:
scores = [25, 50, 75]
names = ['john','james','femi']
classroom = ['ss1a','ss1b','ss1c']
sc = scores[0]
nm = names[0]
cr = classroom[0]

data = { 'john':(25,'ss1a'),'james':(50,'ss1b'),'femi':(75,'ss1c') }
 
dt = data['john']
print(dt)

(25, 'ss1a')


### Functions

In [31]:
def evenOdd(num):
    if num%2 == 0:
        print('Even')
    else:
        print('Old')

In [38]:
evenOdd(110363673634)

Even


In [47]:
x = 'abcd' # Global variable
def doSomething():
    x = '1234' 
    y = 'yes'
    print(x)

doSomething()
print(x)


1234
abcd


In [65]:
def smallest(num1,num2):
    return min([num1,num2])

def smallest2(num1,num2=0):
    return min([num1,num2])

sm = smallest2(-10)
sm2 = smallest2(num1=40)
print(sm2)

0


In [71]:
def smallest3(*nums):
    return min(nums)
    
    
smallest3(3,5,6,7,-4,5,6,7)

-4

In [1]:
import numpy as np
pt = np.random.rand(3)
print(pt)

[ 0.75509981  0.82701409  0.06205945]


In [8]:
import numpy as np
import time

def getPie(N):
    n = 0;
    r = 1
    for i in range(N):
        pt = np.random.rand(2)
        x = 2*pt[0] - 1
        y = 2*pt[1] - 1
#         x = pt[0]
#         y = pt[1]
        if x**2 + y**2 <= r**2:
            n += 1
    p = 4*n/N
    return p

def getPie2(N):
    n = 0
    r = 1
    nums = (2*np.random.rand(N,2) - 1)**2
    fc = np.sum(nums,axis=1)
    n = len(fc[fc <= 1])
    p = 4*n/N
    return p
# st = time.time()
pi = getPie(1000000)
# sp = time.time()
# print(pi)
# print(sp-st)
# st = time.time()
# pi = getPie2(10000000)
# sp = time.time()
print(pi)
# print(sp-st)
        

3.142372


In [57]:
nums = (2*np.random.rand(10000000,2) - 1)**2
print(nums)

[[ 0.03369602  0.25834572]
 [ 0.369889    0.44684827]
 [ 0.02510147  0.92227755]
 ..., 
 [ 0.03677695  0.28731126]
 [ 0.03219372  0.54808335]
 [ 0.06999544  0.12548338]]


In [101]:
def lessThan4(aList):
    result = []
    for item in aList:
        if len(item) < 4:
            result.append(item)
    return result

part = lessThan4(["apple","cat","dog","banana"])
print(part)

    

['cat', 'dog']


In [4]:
nums = (2*np.random.rand(10,2) - 1)**2
print(nums)

[[ 0.54824477  0.11582297]
 [ 0.3677918   0.76233602]
 [ 0.04013749  0.0788348 ]
 [ 0.45984261  0.30263654]
 [ 0.32854921  0.85200424]
 [ 0.34560489  0.0012285 ]
 [ 0.33176928  0.00444845]
 [ 0.00593946  0.0735871 ]
 [ 0.11287906  0.81444049]
 [ 0.73999776  0.04065932]]


In [6]:
np.random.rand(100,2)

array([[ 0.5428225 ,  0.69971176],
       [ 0.85188533,  0.04135257],
       [ 0.58949483,  0.40184303],
       [ 0.55172068,  0.41261487],
       [ 0.62748575,  0.70224907],
       [ 0.62503617,  0.83098022],
       [ 0.06304818,  0.78947181],
       [ 0.05946961,  0.31409096],
       [ 0.44564014,  0.17291997],
       [ 0.62426361,  0.20413148],
       [ 0.26820632,  0.23839837],
       [ 0.97418901,  0.80843484],
       [ 0.05225232,  0.16999652],
       [ 0.74301853,  0.98370142],
       [ 0.43755129,  0.76287217],
       [ 0.30164945,  0.64842134],
       [ 0.72706605,  0.78374998],
       [ 0.05190039,  0.02094989],
       [ 0.91294946,  0.08843906],
       [ 0.86462271,  0.12872052],
       [ 0.0430617 ,  0.25188272],
       [ 0.24342926,  0.82930306],
       [ 0.05473563,  0.81428832],
       [ 0.47655797,  0.96480843],
       [ 0.20816291,  0.17922924],
       [ 0.35658179,  0.34878147],
       [ 0.82640711,  0.79330255],
       [ 0.72642045,  0.48326086],
       [ 0.97486116,